In [7]:
print('hello JP')
print('this is my first notebook from vs code')

hello JP
this is my first notebook from vs code


In [8]:
print('rohitasw')

rohitasw


In [1]:
import numpy as np

In [2]:
l=np.array([1,2,3])
print(l)

[1 2 3]


In [11]:
l.ndim

1

In [12]:
print(l.shape)

(3,)


In [13]:
a = np.arange(15).reshape(3, 5)
print(a)



print(a.shape)

print(a.ndim)

print(a.dtype.name)

print(a.itemsize)

print(a.size)

print(type(a))

b = np.array([6, 7, 8])
print(b)

print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>
