In [2]:
import numpy as np
from numpy.core.fromnumeric import reshape

numpy ndarray object

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
a1 = np.array([[1,2,3],[4,5,6]])
print("\n",a1)


 [[1 2 3]
 [4 5 6]]


ndnimm parameter

In [5]:
a2 = np.array([1,2,3,4,5,6],ndmin=2)
print(a2)

[[1 2 3 4 5 6]]


dtype parameter 

In [6]:
a3 = np.array([1,2,3],dtype=complex) 
print(a3)

[1.+0.j 2.+0.j 3.+0.j]


ndarray.shape attribute<br>
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [7]:
print(a1.shape)

(2, 3)


reshape

In [8]:
a1.shape=(3,2)
print(a1)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
b1 = a1.reshape(3,2)
print(b1)

[[1 2]
 [3 4]
 [5 6]]


ndarray.ndim<br>
This array attribute returns the number of array dimensions.

In [10]:
print("\n",a1.ndim)


 2


numpy.itemsize<br>
This array attribute returns the length of each element of array in bytes.

In [11]:
print(a1.itemsize)

4


numpy.flags<br>
The ndarray object has the following attributes. Its current values are returned by this function.

In [12]:
x = np.array([1,2,3,4,5]) 
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



numpy.empty<br>
It creates an uninitialized array of specified shape and dtype. It uses the following constructor −

In [13]:
x1 = np.empty([3,2], dtype = int) 
print(x1)

[[0 0]
 [0 0]
 [0 0]]


In [14]:
x2 = np.ones([2,2], dtype = int) 
print("\n",x2)


 [[1 1]
 [1 1]]


numpy.asarray<br>
This function is similar to numpy.array except for the fact that it has fewer parameters. <br>
This routine is useful for converting Python sequence into ndarray.

In [15]:
x3 = [1,2,3]

In [16]:
print("\n",np.asarray(x3))


 [1 2 3]


In [17]:
x4 = (1,2,3)
print("\n",np.asarray(x4))


 [1 2 3]


numpy.frombuffer<br>
This function interprets a buffer as one-dimensional array. <br>
Any object that exposes the buffer interface is used as parameter to return an ndarray.

In [18]:
s = b'Hello World' 
print("\n",np.frombuffer(s,dtype='S1'))


 [b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


numpy.fromiter<br>
This function builds an ndarray object from any iterable object. <br>
A new one-dimensional array is returned by this function.

In [19]:
list= range(1,5)
print(list)

range(1, 5)


In [20]:
it = iter(list)  

In [21]:
print(np.fromiter(it, dtype = float))

[1. 2. 3. 4.]


numpy.arange<br>
This function returns an ndarray object containing evenly spaced values within a given range. <br>
The format of the function is as follows −

numpy.arange(start, stop, step, dtype)

In [22]:
x5 = np.arange(10,50,2,dtype=int)

In [23]:
print(x5)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


numpy.linspace<br>
This function is similar to arange() function. In this function, instead of step size, <br>
the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

In [24]:
x6  = np.linspace(10,20,5)
print(x6)

[10.  12.5 15.  17.5 20. ]


In [25]:
x7 = np.linspace(10,20,5,endpoint=False,retstep=True)
print(x7)

(array([10., 12., 14., 16., 18.]), 2.0)


numpy.logspace<br>
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. <br>
Start and stop endpoints of the scale are indices of the base, usually 10.

numpy.logspace(start, stop, num, endpoint, base, dtype)

In [26]:
x8 = np.logspace(1.0, 2.0, num = 10) 
print(x8)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [27]:
x9 = np.logspace(1,10,num=10,base=2)
print(x9)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
