In [2]:
import numpy as np

In [2]:
a=np.arange(6)
print(a)                                     #1D array

[0 1 2 3 4 5]


In [2]:
print(np.arange(12).reshape(4,3))              #2D array

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
print(np.arange(1,25).reshape(2,3,4))            #3D array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [8]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [10]:
a=np.arange(10000).reshape(100,100)
print(a)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [13]:
#to print entire array, we can change the printing option using set_print options.