In [2]:
import numpy as np

In [4]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [4]:
c=a-b
print(c)

[20 29 38 47]


In [15]:
d=sum(a,b)
print(d)
e=b**2
print(e)

[140 141 142 143]
[0 1 4 9]


In [8]:
f=10*np.sin(a)
print(f)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [10]:
print(a)
print(a<35)

[20 30 40 50]
[ True  True False False]


In [11]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
C=A*B                                             # element-wise product
print(C)

[[2 0]
 [0 4]]


In [12]:
print(A@B)                       #Matrix product


[[5 4]
 [3 4]]


In [13]:
print(A.dot(B))                 # dot product

[[5 4]
 [3 4]]


In [13]:
# some operations such as += and *= act in place to modify an existing array rather than create a new one. 

rg=np.random.default_rng(1)
g=np.ones((2,3),dtype=int)

h= rg.random((2,3))
g*=3
print(g)

[[3 3 3]
 [3 3 3]]


In [14]:
h+=g
print(h)

[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [26]:
#UPCASTING
from numpy import pi

i=np.ones(3,dtype=np.int32)
j=np.linspace(0,2*pi,3)
print(j.dtype.name)
print(j)

k=np.exp(j*1j)
print(k.dtype.name)
print(k)

float64
[0.         3.14159265 6.28318531]
complex128
[ 1.+0.0000000e+00j -1.+1.2246468e-16j  1.-2.4492936e-16j]


In [30]:
#URINARY OPERATIONS:

l=rg.random((2,3))
print(l)
print(l.sum())
print(l.min())
print(l.max())

[[0.96165719 0.72478994 0.54122686]
 [0.2768912  0.16065201 0.96992541]]
3.635142616021385
0.16065200877512686
0.9699254132161326


In [33]:
# By specifying the axix parameter you can apply an operation along the specified axis of an array.

m=np.arange(12).reshape(3,4)
print(m)
print("         /////////////////////               ")
print(m.sum(axis=0))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
         /////////////////////               
[12 15 18 21]
