In [2]:
import numpy as np

In [6]:
a=np.arange(1,6)**3

print("         /////////////////////               ")
print(a)
print(a[2])
print(a[2:5])
print(a[1:6:2])
print("         -----------------------              ")
for i in a:
    print(i**(1/3))
print("         -----------------------   ---------------------           ")

print(np.arange(i))


         /////////////////////               
[  1   8  27  64 125]
27
[ 27  64 125]
[ 8 64]
         -----------------------              
1.0
2.0
3.0
3.9999999999999996
5.0
         -----------------------   ---------------------           
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124]


In [14]:
# multidimensional array can have one index per axis. these indices are given in a tupil separated by commas:
def f(x,y):
    return 10*x+y

b=np.fromfunction(f,(5,6),dtype=int)
print(b)
print("         -----------------------              ")

print(b[2,3])

print("         -----------------------              ")
print(b[0:5,1])
print(b[:,1])


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]]
         -----------------------              
23
         -----------------------              
[ 1 11 21 31 41]
[ 1 11 21 31 41]


In [16]:
print(b[1:3,:])
print(b[-1])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[40 41 42 43 44 45]
